# -*- coding: utf-8 -*-
"""Copia de ecNatur 16ene23.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1II1yDjo9xUYSwg0x_iTziOijYV-jg0xx
"""

import cv2
import numpy as np
from google.colab.patches import cv2_imshow
import math

def ec(img,x,y,l,a,sl,da,n):
    if n<=0:
        return


    x2=x+l
    y2=y
    ar=math.radians(a)

    coseno=math.cos(ar)
    seno=math.sin(ar)
    xrot= (x2-x)*seno + (y2-y)*coseno
    yrot= (x2-x)*coseno - (y2-y)*seno

    x2=xrot + x
    y2=yrot + y

    cv2.line(img, (int(x),int(y)), (int(x2),int(y2)), (255,255,0), (1))    
##1
   # ec(img,x2,y2,l*sl,a-da,sl,da,n-1)
   # ec(img,x2,y2,l*sl,a+da,sl,da,n-1)    # ec(img,(x2+x)/2,(y2+y)/2,l*sl,a+da,sl,da,n-1)
   # ec(img,x2,y2,l*sl,a,sl,da,n-1)

##2
    #ec(img,x,y,l*sl,a-da,sl,da,n-1)

##3
    #if(y>280):return
    #ec(img,x2,y2,l*sl,a-da,sl,da,n-1)
    #ec(img,x2,y2,l*sl,a-2*da,sl,da,n-1)
    #ec(img,x2,y2,l*sl,a-3*da,sl,da,n-1)

##4
    #cv2.circle(img,(int(x),int(y)),int(l),(255,255,255),-1)
    #cv2.circle(img,(int(x),int(y)),int(l),(0,0,0),1)
    #ec(img,x2,y2,l*sl,a-da,sl,da,n-1)
    #ec(img,x2,y2,l*sl,a-2*da,sl,da,n-1)
    #ec(img,x2,y2,l*sl,a-3*da,sl,da,n-1)

##5
    ec(img,x2,y2,l+sl,a+da,sl,da,n-1)
    return

img = np.zeros((500, 500, 3), dtype="uint8")
img[:]=(255,255,255)
#1
#ec(img,250,480,150,180,0.7,20,8)
#ec(img,250,480,150,180,0.7,20,8)

##2
#ec(img,250,250,15,180,1.1,20,50)

##3
#ec(img,10,280,150,120,0.8,20,5)

##4
#ec(img,10,180,150,120,0.8,30,7)

##5
ec(img,150,350,10,30,1,50,250)


cv2_imshow(img)

